name: Generate ASCII 
on: push
jobs:
  ascii_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses:  actions/checkout@v5
      
      - name: List Repo Files
        run: ls 

      - name: Executing Shell Script
        run: |
          chmod +x ./ascii-schell.sh
          ./ascii-schell.sh